from tkinter import *

window = Tk()
window.title("Calculator")



label = Label(window, text="Enter your number:",bg='gray',width=20)
btn7 = Button(text='7',width=3)
btn8 = Button(text='8',width=3)
btn9 = Button(text='9',width=3)
btn0 = Button(text='0',width=10)
btn1 = Button(text='1',width=3)
btn2 = Button(text='2',width=3)
btn3 = Button(text='3',width=3)
btn4 = Button(text='4',width=3)
btn5 = Button(text='5',width=3)
btn6 = Button(text='6',width=3)
btnM = Button(text='*',width=3)
btnS = Button(text='+',width=3)
btnD = Button(text='-',width=3)
btnL = Button(text='/',width=3)
btnDt = Button(text='.',width=3)
btnE = Button(text='=',width=3)

label.grid(row=0,column=0,columnspan=4)
btn7.grid(row=1,column=0,padx=5)
btn8.grid(row=1,column=1,padx=5)
btn9.grid(row=1,column=2,padx=5)
btnS.grid(row=1,column=3,padx=5)
btn4.grid(row=2,column=0,padx=5)
btn5.grid(row=2,column=1,padx=5)
btn6.grid(row=2,column=2,padx=5)
btnD.grid(row=2,column=3,padx=5)
btn1.grid(row=3,column=0,padx=5)
btn2.grid(row=3,column=1,padx=5)
btn3.grid(row=3,column=2,padx=5)
btnM.grid(row=3,column=3,padx=5)
btn0.grid(row=4,column=0,columnspan=2,padx=5)
btnDt.grid(row=4,column=2,padx=5)
btnL.grid(row=4,column=3,padx=5)
btnE.grid(row=5,column=3,padx=5)

window.mainloop()